using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Guess the Number!");
            Console.WriteLine("By Connor Turner!");
            Console.WriteLine("");
            Console.WriteLine("Guess a random number generated by the computer!");
            Console.WriteLine("enter a number to guess between 1 and 100");

            Random rnd = new Random();
            int secretNumber= rnd.Next(1,101);
            //Console.WriteLine("our secret number is " + secretNumber);

            int guess = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("you guessed " + guess);

            if (secretNumber == guess)
            {
                Console.WriteLine("Correct! Well Done!");
            }
            else
            {
                Console.WriteLine("Wrong! try again!");
                
                if (secretNumber< guess)
                {
                    Console.WriteLine("the secret number is less than your guess");
                }
                else
                {
                    Console.WriteLine("the sevret number is bigger than your guess");
                }
            }
            


            Console.ReadKey();

        }
    }
}

