using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Guess the Number!");
            Console.WriteLine("By Connor Turner!");
            Console.WriteLine("");
            Console.WriteLine("Guess a random number generated by the computer!");
            Console.WriteLine("enter a number to guess between 1 and 10");

            Random rnd = new Random();
            int secretNumber= rnd.Next(1,10);
            //Console.WriteLine("our secret number is " + secretNumber);

            int guess = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("you guessed " + guess);
            int numberofguess = 0;
            if (secretNumber == guess)
            {
                Console.WriteLine("Correct! Well Done!");
            }
         

          

            while (guess != secretNumber)
            {
                //keep guessing

                //first this will inform the player they are wrong
                Console.WriteLine("Wrong! try again!");
                if (guess != secretNumber)
                {
                    numberofguess++;
                }
                    if (secretNumber < guess)
                {
                    Console.WriteLine("the secret number is less than your guess");
                }
                else
                {
                    Console.WriteLine("the secret number is bigger than your guess");
                }
                //read a new guess from the player
                Console.WriteLine("guess anouther number!");
                guess = Convert.ToInt32(Console.ReadLine());

            }

            // now we have guessed the correct number
            Console.WriteLine("Correct! Well Done! it took you " +numberofguess + " tries!");

            Console.ReadKey();

        }
    }
}

