using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Guess the Number!");
            Console.WriteLine("By Connor Turner!");
            Console.WriteLine("");
            

            bool keepplaying = true;
            while (keepplaying == true)
            {


                Random rnd = new Random();
                int secretNumber = rnd.Next(1, 10);
                //Console.WriteLine("our secret number is " + secretNumber);
                Console.WriteLine("Guess a random number generated by the computer!");
                Console.WriteLine("enter a number to guess between 1 and 10");
                int guess = Convert.ToInt32(Console.ReadLine());
                Console.WriteLine("you guessed " + guess);
                int numberofguess = 1;
                if (secretNumber == guess)
                {
                    Console.WriteLine("Correct! Well Done!");
                }




                while (guess != secretNumber & numberofguess == 5)
                {
                    //keep guessing

                    //first this will inform the player they are wrong
                    Console.WriteLine("Wrong! try again!");
                    if (guess != secretNumber)
                    {
                        ++numberofguess;
                    }
                    if (secretNumber < guess)
                    {
                        Console.WriteLine("the secret number is less than your guess");
                    }
                    else
                    {
                        Console.WriteLine("the secret number is bigger than your guess");
                    }
                    if (numberofguess == 5)
                    {
                        Console.WriteLine("you have guessed too many times");
                        
                    }
                    //read a new guess from the player
                    Console.WriteLine("guess anouther number!");
                    guess = Convert.ToInt32(Console.ReadLine());

                }
            
                // now we have guessed the correct number
                Console.WriteLine("Correct! Well Done! it took you " + numberofguess + " tries!");

                //ask if they want to play again
                Console.WriteLine("play again? (y/n)");
                string restartresponce = Console.ReadLine();

                if (restartresponce == "y")
                {
                    //restart the game
                    keepplaying = true;
                }
                else
                {
                    //exit the game
                    keepplaying = false;
                }

            }//end of the while loop
           

        }
    }
}

